// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iDss.X.Data;

#nullable disable

namespace iDss.X.Migrations.PriceDb
{
    [DbContext(typeof(PriceDbContext))]
    partial class PriceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iDss.X.Models.GeneralPrice", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<decimal?>("addprice")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("createdby")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("createddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("descode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("destype")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("flag")
                        .HasColumnType("int");

                    b.Property<int?>("maxpiece")
                        .HasColumnType("int");

                    b.Property<decimal?>("maxweight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("minpiece")
                        .HasColumnType("int");

                    b.Property<decimal?>("minweight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("modifieddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("modifier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("oricode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("oritype")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("service")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("slafrom")
                        .HasColumnType("int");

                    b.Property<int?>("slato")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("pri_pricegeneral");
                });
#pragma warning restore 612, 618
        }
    }
}
